"""empty message

Revision ID: 762eb0168607
Revises: ccb6f89c8fdc
Create Date: 2020-11-22 16:48:16.654055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762eb0168607'
down_revision = 'ccb6f89c8fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('booking', sa.Column('seats', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'booking', 'seats', ['seats'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'seats')
    op.drop_table('seats')
    # ### end Alembic commands ###
